blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/pallepadehat/DockBricks/discussions
    about: Please use GitHub Discussions for usage questions and general help.
